version: "3"
services:
  database:
    image: postgres:10.10-alpine
    container_name: eShop_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: eShop
      POSTGRES_PASSWORD: eShop
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: eshop_db
    restart: always
